# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68bdd40a54576aa837ce50ef668552b5df08f4aff969f5a5611b61f95ab66704138f7bc52af8f83fff7dd3b9af3607727e72901f0f5555839817cc6eee71f96c

test:
  secret_key_base: 1f29fb05d84f7f93c8af422859c1d38d24804eb4fa9b13295d9faec6546baae10f533d72b311b35c8fe6548ac5a976184f78458a4522f04a0556f7643d716091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
